/**
 * Mongoose schema for wallet sign-in nonces.
 *
 * Previously stored in an in-memory Map, which does not survive across
 * Vercel serverless function instances — a nonce generated by one
 * instance would be invisible to a different instance handling the
 * follow-up signature verification request, causing intermittent
 * "invalid or expired nonce" failures. Storing the nonce in MongoDB
 * makes it visible to every instance, the same fix already applied to
 * rate limiting.
 */

import mongoose, { Schema, type Document, type Model } from "mongoose";

export interface NonceDocument extends Document {
  walletAddress: string; // lowercase 0x address
  nonce: string;
  issuedAt: number; // ms epoch
}

const NonceSchema = new Schema<NonceDocument>({
  walletAddress: { type: String, required: true, unique: true, index: true },
  nonce: { type: String, required: true },
  issuedAt: { type: Number, required: true },
});

export const NonceModel: Model<NonceDocument> =
  mongoose.models.Nonce || mongoose.model<NonceDocument>("Nonce", NonceSchema);
